services:
  - type: web
    name: studysync
    runtime: node
    repo: https://github.com/HusseinSelim-1977/StudySync-1
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://studysync-gateway.onrender.com
